#!/bin/sh

SYNERGY_SERVER=/Applications/Synergy.app/Contents/MacOS/synergys
SYNERGY_CONFIG=~/Library/Application\ Support/Synergy/Synergy/LastConfig.cfg
# use this one to pass --name or other arguments
SYNERGY_FLAGS=''

"${SYNERGY_SERVER}" -f --debug INFO --config "${SYNERGY_CONFIG}" ${SYNERGY_FLAGS} --enable-crypto | while read line; do
  if echo $line | grep entering; then
    echo mouse is back
    ~/bin/m1ddc set input 15
  fi
  if echo $line | grep leaving; then
    echo mouse just left
    ~/bin/m1ddc set input 16
  fi
done
